apiVersion: v1
kind: Namespace
metadata: 
  name: nimbus
  
  labels:
    app.kubernetes.io/name: nimbus
    app.kubernetes.io/part-of: nimbus
    app.kubernetes.io/managed-by: argo-cd
    environment: dev